/** Generated by script/vite-plugin-share-image-sizes.mjs at build time. */
declare module "virtual:share-image-sizes" {
  /** Site-absolute asset path (`/assets/foo.jpg`) to its intrinsic pixel size. */
  const shareImageSizes: Record<string, { width: number; height: number }>;
  export default shareImageSizes;
}
